GET http://localhost:8000/users

###

POST http://localhost:8000/users
Content-Type: application/json

{
    "email": "flavio@test.com",
    "password": "stefano"
}

###

GET http://localhost:8000/users/2

###

POST http://localhost:8000/auth/token
Content-Type: application/json

{
    "email": "flavio@test.com",
    "password": "stefano"
}

###

GET http://localhost:8000/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMiIsImVtYWlsIjoiZmxhdmlvQHRlc3QuY29tIiwiZXhwIjoxNzU5NDk0NTE1LCJpc19yZWZyZXNoIjp0cnVlfQ.lGadBQ53BYzYgzj41UPz41yHqQgvI2UV1B_BOdQw6SA

###

GET http://localhost:8000/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMiIsImVtYWlsIjoiZmxhdmlvQHRlc3QuY29tIiwiZXhwIjoxNzU5NDEzMDAwfQ.9BTPhu076FqndV2HsEZ77qfcuT_ZdFywe0vQbqzcUXY