GET http://localhost:8000/users

###

POST http://localhost:8000/users
Content-Type: application/json

{
    "email": "stefano@test.com",
    "password": "stefano",
    "role": "ADMIN"
}

###

GET http://localhost:8000/users/3

###

POST http://localhost:8000/auth/token
Content-Type: application/json

{
    "email": "stefano@test.com",
    "password": "stefano"
}

###

GET http://localhost:8000/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiZW1haWwiOiJzdGVmYW5vQHRlc3QuY29tIiwicm9sZSI6IkFETUlOIiwiZXhwIjoxNzU5NTAwOTQyLCJpc19yZWZyZXNoIjp0cnVlfQ.iAhRYvOyYvB2HVeOi6AGk2WnRT2i2gLwbUxoZLdgrGg

###

GET http://localhost:8000/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiZW1haWwiOiJzdGVmYW5vQHRlc3QuY29tIiwicm9sZSI6IkFETUlOIiwiZXhwIjoxNzU5NDE4MTUzfQ.9isp6O5iCJ-rmWYQA9spz3ClH-I_Hp1T8MsMmJDdr5o