
# List all users
GET http://localhost:8000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwicm9sZSI6IkFETUlOIiwiZXhwIjoxNzU5NDg5NjA0fQ.8VxfqJNIO9OHoYEdpKu8NfDSJE4lgVkzfBwPB3UDY_s

###

# Create User
POST http://localhost:8000/users
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "test",
    "role": "ADMIN"
}

###

# User by id
GET http://localhost:8000/users/3

###

# Login
POST http://localhost:8000/auth/token
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "test"
}

###

# refresh
GET http://localhost:8000/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwicm9sZSI6IkFETUlOIiwiZXhwIjoxNzU5NTY1MTY5LCJpc19yZWZyZXNoIjp0cnVlfQ.wDwOJwskF8J-DMceh5gDkJ_3QS0kd5CxiHW-IQFVJ6s
###

# who am i
GET http://localhost:8000/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwicm9sZSI6IkFETUlOIiwiZXhwIjoxNzU5NDg5NjA0fQ.8VxfqJNIO9OHoYEdpKu8NfDSJE4lgVkzfBwPB3UDY_s

###

# Create Order
POST http://localhost:8000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwicm9sZSI6IkFETUlOIiwiZXhwIjoxNzU5NDg2MzIzfQ.aRRsDhLXjzy4Nt3QqQ3aayeOZO-ooUlZqApwGI7z2TQ
Content-Type: application/json

{
    "amount": 100
}