services:
  db:
    image: postgres
    container_name: jwt_postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    volumes:
      - C:/Users/stefano/Desktop/psql_data:/var/lib/postgresql
  
  api:
    build: ./api
    container_name: jwt_fastapi
    env_file:
      - ./.env
    ports:
      - "80:8000"
    depends_on:
      - db
