"""user role

Revision ID: 27ea899344ef
Revises: 92774ab67e5c
Create Date: 2025-10-02 16:01:49.089265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27ea899344ef'
down_revision: Union[str, Sequence[str], None] = '92774ab67e5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    roles_enum = sa.Enum('USER', 'ADMIN', name='roles')
    roles_enum.create(op.get_bind())
    op.add_column('users', sa.Column('role', roles_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    sa.Enum(name='roles').drop(op.get_bind())
    # ### end Alembic commands ###
